ex:('type' -> (nat    -> (nat<=int[is>0]),
               large  -> (large<=int[is>99],
                          large<=nat[is>99]),
               names  -> (names:(str,str)),
               user   -> (user:('id'->int,'login'->str),
                          user<=person[put,'id',.age][put,'login',.name][as,user]),
               person -> (person:('name'->str,'age'->nat),
                          person<=('name'->str,'age'->int)[as,person],
                          person<=('name'->str)[put,'age',1][as,person],
                          person<=names-<('name'-><y>.0+<.y>.1,'age'->1)[as,person],
                          person<=str-<('name'->_,'age'->nat:1))))<=mm