:imagesdir: ./images/reference

== Reference

=== mmlang Grammar

[source]
----
include::images/reference/mmlang.ebnf[]
----

++++
<iframe src="images/reference/mmlang-ebnf.html" width="100%" height="1000px"></iframe>
++++

The following https://en.wikipedia.org/wiki/Axiomatic_semantics[language axioms] have variables:

[.small]
[cols="2,1",width=25%,grid=none,frame=none]
|===
| variable | range

| `o1`, `o2`, ...     | `objs`
| `t1`, `t2`, ...     | types
| `v1`, `v2`, ...     | values
| `[a]`, `[b]`, ...   | instructions
| `{q1}`, `{q2}`, ... | quantifiers
|===

[source]
----
id(t1)                    := t1<=t1[id]
domain(t1)                := t1
range(t1)                 := t1
domain(t2<=t1[a])         := t1
range(t2<=t1[a])          := t2
----

The quantifiers of an `mmlang` program are elements of a https://en.wikipedia.org/wiki/Ring_(mathematics)[ring with unity] called the _quantifier ring_. In the equations to follow, `*` and `+` refer to the respective monoid and group operations the quantifier ring.

* The `obj` magma juxtapositions, where instructions `[a]`, `[b]`, etc. act as https://en.wikipedia.org/wiki/Function_(mathematics)[functions] on values and as free monoid concatenation on types. The particulars `objs` that are yielded juxtaposing an `obj` to the left of a type are forthcoming.

[source]
----
v1{q1}                v2{q2}               := v2{q1*q2}
v1{q1}                t2{q2}<=t1[a][b]     := b(a(v1)){q1*q2}
t2{q1}<=t1[a][b]      t3{q2}<=t2[c][d]     := t3{q1*q2}<=t1[a][b][c][d]
t2{q1}<=t1[a][b]      v1{q2}               := v1{q1*q2}
----

* The `inst` instructions denote functions that operate on `objs`. The particular of each instruction is forthcoming. The branch instructions denote flow control operations that mirror the type ringoid where `[compose]` is `*`, `[branch]` is `+`, and `[choose]` is `|`.

[source]
----
v1{q1}[compose,t2{q2}<=t1[a][b],t3{q3}<=t2[c][d]]]     := t3{q1*q2*q3}<=t1[a][b][c][d](v1)
v1{q1}[branch,t2{q2}<=t1[a][b],t2{q3}<=t1[c][d]]       := t2{q1*q2}<=t1[a][b](v1),t2{q1*q2}<=t1[c][d](v1)
v1{q1}[branch,t2{q2}<=t1[a][b],t2{q3}<=t1[a][b]]       := t2{q1*(q2+q3)}<=t1[a][b][c][d](v1)
v1{q1}[choose,t2{q2}<=t1[a][b],t2{q3}<=t1[c][d]]       := t2{q1*q2}<=t1[a][b](v1) | t2{q1*q2}<=t1[c][d](v1)
v1{q1}[repeat,[obj{?}->{0},obj{?}->type,n]]            := ...
----

* The `polys` are the free algebra of the branch operations encoded in `mmlang` itself. Thus, the `inst` branch rules above are mirrored in the `poly` compositions below.

[source]
----
(t2{q1}<=t1[a][b];t3{q2}<=t2[c][d])  := t3{q1*q2}[a][b][c][d]
(t2{q1}<=t1[a][b],t2{q2}<=t1[c][d])  := t2{q1+q2}<=t1[branch,t2{q1}<=t1[a][b],t2{q1}<=t1[c][d]]
(t2{q1}<=t1[a][b],t2{q2}<=t1[a][b])  := t2{q1+q2}<=t1[a][b]
(t2{q1}<=t1[a][b]|t2{q2}<=t1[c][d])  := t2{min(q1,q2),max(q1,q2)}<=t1[choose,t2{q1}<=t1[a][b],t2{q2}<=t1[c][d]]
----

* The non-branching `inst` instructions are the functional primitives that are composed to create mm-ADT programs.

[source]
----
obj    type                     := operation or equivalence
--------------------------------------------------------
o1     bool<=obj[a,o2]          := o1.test(o2)
bool1  bool<=bool[and,bool2]    := bool1 & bool2
o1{q1} int<=obj[count]          := q1
o1     bool<=obj[eq,o2]         := o1 == o2
t1     str<=obj[explain]        ...
...
----

* The type-oriented `inst` instructions specify the typing rules, where the `_` symbol refers to the __anonymous type__. These equations are presented using the `obj` magma's juxtaposition.

[source]
----
t1    _                     := t1
t1    _[a][b]               := b(a(t1))<=t1[a][b]
o1    [a,_]                 := true
o1    [a,o1]                := true
o1{0} [a,{0}]               := true
o1    [a,t1]                := t1(o1) != {0}
----


=== Instructions

The mm-ADT VM https://en.wikipedia.org/wiki/Instruction_set_architecture[instruction set architecture] is presented below, where the instructions are ordered by their classification and within each classification, they are ordered alphabetically.

.Instruction classes
[cols="^1h,4,6",width=80%]
|===
| Class      | Signature                  | Description

| Branch     | `y{*}\<=x[branch]`         | Split `objs` across instructions.
| Filter     | `x{?}\<=x[filter]`         | Remove `objs` from an evaluation
| Flatmap    | `y{*}\<=x[flatmap]`        | Split `objs` across objects.
| Initial    | `obj{0}\<=x[initial]`      | Finalize `objs` in an evaluation
| Map        | `y\<=x[map]`               | Move `objs` between objects
| Reduce     | `y\<=x{*}[reduce]`         | Fold `objs` down to a single `obj`
| SideEffect | `x\<=x[sideeffect]`        | Global state mutations
| Terminal   | `x{*}\<=obj{0}[terminal]`  | Generate `objs` for evaluation
| Trace      | `y\<=x[trace]`             | Traverser the `obj` graph (reflection)
|===

==== Branch Instructions

The branch instruction support the splitting and merging of parallel, data flows, where each branch is a type and, depending on the particular branch instruction, some types, all types, or only those types given a predicate are evaluated.

===== [compose]
===== [branch]
===== [choose]

==== Filter Instructions
==== Map Instructions
==== Reduce Instructions
==== Trace Instructions

