:imagesdir: ./images/reference

== Reference

=== mmlang Grammar

[source]
----
include::images/reference/mmlang.ebnf[]
----

++++
<iframe src="images/reference/mmlang-ebnf.html" width="100%" height="1000px"></iframe>
++++

////
The following https://en.wikipedia.org/wiki/Axiomatic_semantics[language axioms] have variables:

[.small]
[cols="2,1",width=25%,grid=none,frame=none]
|===
| variable | range

| `o1`, `o2`, ...     | `objs`
| `t1`, `t2`, ...     | types
| `v1`, `v2`, ...     | values
| `[a]`, `[b]`, ...   | instructions
| `{q1}`, `{q2}`, ... | quantifiers
|===

[source]
----
id(t1)                    := t1<=t1[id]
domain(t1)                := t1
range(t1)                 := t1
domain(t2<=t1[a])         := t1
range(t2<=t1[a])          := t2
----

The quantifiers of an `mmlang` program are elements of a https://en.wikipedia.org/wiki/Ring_(mathematics)[ring with unity] called the _quantifier ring_. In the equations to follow, `*` and `+` refer to the respective monoid and group operations the quantifier ring.

* The `obj` magma juxtapositions, where instructions `[a]`, `[b]`, etc. act as https://en.wikipedia.org/wiki/Function_(mathematics)[functions] on values and as free monoid concatenation on types. The particulars `objs` that are yielded juxtaposing an `obj` to the left of a type are forthcoming.

[source]
----
v1{q1}                v2{q2}               := v2{q1*q2}
v1{q1}                t2{q2}<=t1[a][b]     := b(a(v1)){q1*q2}
t2{q1}<=t1[a][b]      t3{q2}<=t2[c][d]     := t3{q1*q2}<=t1[a][b][c][d]
t2{q1}<=t1[a][b]      v1{q2}               := v1{q1*q2}
----

* The `inst` instructions denote functions that operate on `objs`. The particular of each instruction is forthcoming. The branch instructions denote flow control operations that mirror the type ringoid where `[compose]` is `*`, `[branch]` is `+`, and `[choose]` is `|`.

[source]
----
v1{q1}[compose,t2{q2}<=t1[a][b],t3{q3}<=t2[c][d]]]     := t3{q1*q2*q3}<=t1[a][b][c][d](v1)
v1{q1}[branch,t2{q2}<=t1[a][b],t2{q3}<=t1[c][d]]       := t2{q1*q2}<=t1[a][b](v1),t2{q1*q2}<=t1[c][d](v1)
v1{q1}[branch,t2{q2}<=t1[a][b],t2{q3}<=t1[a][b]]       := t2{q1*(q2+q3)}<=t1[a][b][c][d](v1)
v1{q1}[choose,t2{q2}<=t1[a][b],t2{q3}<=t1[c][d]]       := t2{q1*q2}<=t1[a][b](v1) | t2{q1*q2}<=t1[c][d](v1)
v1{q1}[repeat,[obj{?}->{0},obj{?}->type,n]]            := ...
----

* The `polys` are the free algebra of the branch operations encoded in `mmlang` itself. Thus, the `inst` branch rules above are mirrored in the `poly` compositions below.

[source]
----
(t2{q1}<=t1[a][b];t3{q2}<=t2[c][d])  := t3{q1*q2}[a][b][c][d]
(t2{q1}<=t1[a][b],t2{q2}<=t1[c][d])  := t2{q1+q2}<=t1[branch,t2{q1}<=t1[a][b],t2{q1}<=t1[c][d]]
(t2{q1}<=t1[a][b],t2{q2}<=t1[a][b])  := t2{q1+q2}<=t1[a][b]
(t2{q1}<=t1[a][b]|t2{q2}<=t1[c][d])  := t2{min(q1,q2),max(q1,q2)}<=t1[choose,t2{q1}<=t1[a][b],t2{q2}<=t1[c][d]]
----

* The non-branching `inst` instructions are the functional primitives that are composed to create mm-ADT programs.

[source]
----
obj    type                     := operation or equivalence
--------------------------------------------------------
o1     bool<=obj[a,o2]          := o1.test(o2)
bool1  bool<=bool[and,bool2]    := bool1 & bool2
o1{q1} int<=obj[count]          := q1
o1     bool<=obj[eq,o2]         := o1 == o2
t1     str<=obj[explain]        ...
...
----

* The type-oriented `inst` instructions specify the typing rules, where the `_` symbol refers to the __anonymous type__. These equations are presented using the `obj` magma's juxtaposition.

[source]
----
t1    _                     := t1
t1    _[a][b]               := b(a(t1))<=t1[a][b]
o1    [a,_]                 := true
o1    [a,o1]                := true
o1{0} [a,{0}]               := true
o1    [a,t1]                := t1(o1) != {0}
----
////

=== Instructions

The mm-ADT VM https://en.wikipedia.org/wiki/Instruction_set_architecture[instruction set architecture] is presented below, where the instructions are ordered by their classification and within each classification, they are ordered alphabetically.

////
.Instruction classes
[cols="^1h,4,6",width=80%]
|===
| Class      | Signature                  | Description

| Branch     | `y{*}\<=x[branch]`         | Split `objs` across instructions.
| Filter     | `x{?}\<=x[filter]`         | Remove `objs` from an evaluation
| Flatmap    | `y{*}\<=x[flatmap]`        | Split `objs` across objects.
| Initial    | `obj{0}\<=x[initial]`      | Finalize `objs` in an evaluation
| Map        | `y\<=x[map]`               | Move `objs` between objects
| Reduce     | `y\<=x{*}[reduce]`         | Fold `objs` down to a single `obj`
| SideEffect | `x\<=x[sideeffect]`        | Global state mutations
| Terminal   | `x{*}\<=obj{0}[terminal]`  | Generate `objs` for evaluation
| Trace      | `y\<=x[trace]`             | Traverser the `obj` graph (reflection)
|===
////

==== Branch Instructions

Branch instructions enable the splitting, composing, and merging of streams. This subset of `inst` is a particular type of https://en.wikipedia.org/wiki/Additive_category[additive category] called a https://en.wikipedia.org/wiki/Traced_monoidal_category[traced monoidal category], where `[repeat]` provides feedback and each instruction's `poly` arguments are  https://en.wikipedia.org/wiki/Biproduct[biproducts] maintaining both injective and projective morphisms. There exists a well-established graphical language for such monoidal categories that has been adopted in `mmlang` sugar syntax (or as best as can be reasonably captured using https://en.wikipedia.org/wiki/ASCII[ASCII] characters).



[cols="^.^1,^.^2,^.^1,.^5"]
|====
| name | string diagram |  sugar | mmlang example

| initial | image:branch-initial.svg[width=100]  | `A`
a|
[exec]
----
int
6
----
{blank}
| split | image:branch-split.svg[width=130]    | `-<(A,A)`
a|
[exec]
----
int-<(_,_)
6-<(int,int)
----
{blank}

| merge | image:branch-merge.svg[width=130]    | `(A,A)>-`
a|
[exec]
----
(int,int)>-
(6,6)>-
----
{blank}

| repeat | image:branch-repeat.svg[]    | `(A)^(A)`
a|
[exec]
----
int(+3)^(5)
6(+3)^(5)
----
{blank}

| terminal | image:branch-terminal.svg[width=100] | `A{0}`
a|
[exec]
----
int{0}
6{0}
----
{blank}
|====



[cols="^1,.^9,7"]
|====
| inst         | description | example

// BRANCH
| `[branch]` +
`[ ]`
| Juxtapose start across `poly` terms and then aggregate the terms of the resultant `poly` as dictated by the `polys` underlying magma (https://en.wikipedia.org/wiki/Module_(mathematics)[obj~LR~-module]).
\[
x(a_0,a_1,\ldots,a_n) =  \bigodot_{i=0}^{i \leq n} xa_i
\]
a|
[exec,prompt="mm> "]
----
6[branch,(+1,'a',*int)]
6[+1,'a',*int]
----
{blank}

// COMBINE
| `[combine]` +
`=`
| Pairwise juxtapose the terms of two `polys` (https://en.wikipedia.org/wiki/Hadamard_product_(matrices)[Hadamard product] and link:https://en.wikipedia.org/wiki/Polynomial_ring[obj[X]]).
\[
(a_0,\ldots,a_n) \circ (b_0,\ldots,b_n) = (a_0b_0,\ldots,a_nb_n)
\]
a|
[exec,prompt="mm> "]
----
(1;2;3)[combine,(+10;+20;+30)]
(1;2;3)=(+10;+20;+30)
----
{blank}

// LIFT
| `[lift]` +
`<< >>`
| Detach from the `obj` graph and operate stateless. |

// MERGE
| `[merge]` +
`>-`
| Aggregate the terms of the start `poly`, where aggregation semantics is determined by the underlying magma of the `poly` (https://en.wikipedia.org/wiki/Module_(mathematics)[obj~R~-module]).
\[
(a_0,a_1,\ldots,a_n) = \bigodot_{i=0}^{i \leq n} a_i
\]
a|
[exec,prompt="mm> "]
----
(1,2,3)[merge]
(1,2,3)>-
(1;2;3)>-
(1\|2\|3)>-
----
{blank}

// REPEAT
| `[repeat]` +
`( )^( )`
| Apply the first `obj` (typically a type) to the incoming `obj` until the second `obj` is not `{0}`. For ease of  use, if the second `obj` is an `int` value, then this is interpreted as number of times to iterate.

\[
x(a^n) = x \prod^{i \leq n}_{i=0} a
\]
a|
[exec,prompt="mm> "]
----
[1,2,3][repeat,+2,3]
(1,2,3)>-(+2)^(3)
(1,2,3)>-(*2)^(is<10)
----
{blank}


// SPLIT
| `[split]` +
`-<`
| Juxtapose start across `poly` terms as a scalar to a vector. `[branch]` is equivalent to `[split][merge]` (https://en.wikipedia.org/wiki/Module_(mathematics)[obj~L~-module]).
\[
x(a_0,a_1,\ldots,a_n) = (xa_0,xa_1,\ldots,xa_n)
\]
a|
[exec,prompt="mm> "]
----
1[split,(+1,+2,+3)]
1-<(+2,+3,+4)
1-<(+2;+3;+4)
1-<(+2\|+3\|+4)
----
{blank}

| `[swap]` +
`/ /`
| Replace the `[swap]` type's last `inst` argument with the start and the start with the `inst` argument (https://en.wikipedia.org/wiki/Swap_(computer_programming)[swap]).
\[
xa = ax
\]
a|
[exec,prompt="mm> "]
----
'-adt'[plus,'mm']
'-adt'[swap,[plus,'mm']]
'-adt'+'mm'
'-adt'/+'mm'/
----
{blank}

|====

==== Filter Instructions

==== Map Instructions

==== Reduce Instructions

==== Trace Instructions

